\ARG BASE_IMAGE="alpine:3.16"
from ${BASE_IMAGE} as base

RUN apk update \
  && apk add --no-cache \
  argp-standalone \
  bash \
  binutils-dev \
  ca-certificates \
  fts-dev \
  g++ \
  gcc \
  gcovr \
#  gettext-dev \ # for libintl elfutils
#  musl-libintl \
  git \
  curl \
  make \
  m4 \
  musl-legacy-error \
  musl-obstack-dev \
  libunwind-dev \
  libcap-dev \
  libcap \
  netcat-openbsd \
  patch \
  subversion \
  unzip \
  wget \
  cmake \
  xz-dev \ # lzma
  bzip2-dev \
  zlib

SHELL ["/bin/bash", "-c"]

# Version 11 on alpine 16
ENV CC=gcc
ENV CXX=g++

RUN mkdir /patch
ADD error.h.patch /patch
ADD libdw_alloc.c.patch /patch

# Not reinstalling cmake
# default CMake is 3.23 on alpine 16 (which is enough)

# no LLVM for now
from base as ninja

# Ninja build 1.10.2
RUN VERSION="1.10.2" \
  && SHA256="ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed" \
  && curl -LO https://github.com/ninja-build/ninja/archive/refs/tags/v${VERSION}.tar.gz \
  && (printf "${SHA256}  v${VERSION}.tar.gz" | sha256sum -c) \
  && tar xvfz v${VERSION}.tar.gz \
  && cd ninja-${VERSION} \
  && cmake -Bbuild-cmake \
  && cmake --build build-cmake  -j $(nproc) -t install

# google test / google mock
RUN VERSION="1.11.0" \
  && curl -LO https://github.com/google/googletest/archive/refs/tags/release-${VERSION}.tar.gz \
  && SHA256="b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5" \
  && (printf "${SHA256}  release-${VERSION}.tar.gz" | sha256sum -c) \
  && tar xf release-${VERSION}.tar.gz \
  && cd googletest-release-${VERSION} \
  && mkdir build \
  && cd build \
  && cmake -GNinja ../ \
  && cmake --build . -t install \
  && cd ../ \
  && rm -rf googletest-release-${VERSION} release-${VERSION}.tar.gz

# More recent Cpp check 
RUN VERSION="2.8" \
  && curl -LO https://github.com/danmar/cppcheck/archive/refs/tags/${VERSION}.tar.gz \
  && SHA256="57298f3b805f0eb816a04115fbc70e701f75083cfb0305a44246e365cf27606a" \
  && (printf "${SHA256}  ${VERSION}.tar.gz" | sha256sum -c) \
  && tar xf ${VERSION}.tar.gz \
  && cd cppcheck-${VERSION} \
  && mkdir build \
  && cd build \
  && cmake -GNinja ../ \
  && cmake --build . -t install  \
  && cd ../ \
  && rm -rf ${VERSION}.tar.gz cppcheck-${VERSION}

# C++ json library (used for test purpose)
RUN VERSION="3.10.5" \
  && curl -LO https://github.com/nlohmann/json/releases/download/v${VERSION}/json.tar.xz \
  && SHA256="344be97b757a36c5b180f1c8162f6c5f6ebd760b117f6e64b77866e97b217280" \
  && (printf "${SHA256}  json.tar.xz" | sha256sum -c) \
  && tar xf json.tar.xz \
  && cd json \
  && mkdir build && cd build \
  && cmake -GNinja -DJSON_BuildTests=Off ../ \
  && cmake --build . -t install \
  && cd ../ \
  && rm -rf json json.tar.xz

# Google benchmark
RUN VERSION="1.6.1" \
  && curl -LO "https://github.com/google/benchmark/archive/refs/tags/v${VERSION}.tar.gz" \
  && SHA256="6132883bc8c9b0df5375b16ab520fac1a85dc9e4cf5be59480448ece74b278d4" \
  && (printf "${SHA256}  v${VERSION}.tar.gz" | sha256sum -c) \
  && tar xf v${VERSION}.tar.gz \
  && cd benchmark-${VERSION} \
  # python is missing on ubuntu 20.04, use python 3 instead
  && { command -v python > /dev/null || { ln -s /usr/bin/python3 python && export PATH=$PWD:$PATH; }; } \
  && cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_USE_BUNDLED_GTEST=OFF -GNinja -S . -B "build" \
  && cmake --build "build" --target install \
  && cd ../ \
  && rm -rf benchmark-${VERSION} v${VERSION}.tar.gz
