#define YY_event_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from event_parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "event_parser.y"

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "event_config.h"
#include "perf_archmap.hpp"

/*
#define YYSTYPE char *
*/

#define YYDEBUG 0

int yywrap() { return 1;}

typedef struct yy_buffer_state * YY_BUFFER_STATE;
extern int yylex();
extern int yyparse();
extern YY_BUFFER_STATE yy_scan_string(const char * str);
extern void yy_delete_buffer(YY_BUFFER_STATE buffer);

uint8_t mode_from_str(const char *str) {
  uint8_t mode = EVENT_NONE;
  if (!str || !*str)
    return mode;

  size_t sz = sizeof(str);
  for (int i = 0; i < sz; ++i) {
    if (str[i] == 'M' || str[i] == 'm')
      mode |= EVENT_METRIC;
    if (str[i] == 'G' || str[i] == 'g')
      mode |= EVENT_CALLGRAPH;
    if (str[i] == 'A' || str[i] == 'a' || str[i] == '*')
      mode |= EVENT_BOTH;
  }
  return mode;
}

void conf_finalize(EventConf *conf) {
  // Generate label if needed
  // * if both, "<eventname>:<groupname>"
  // * if only event, "<eventname>"
  // * if neither, but id, "id:<id>"
  // * if none, then this is an invalid event anyway
  if (!conf->label) {
    if (conf->eventname && conf->groupname) {
      size_t buf_sz = strlen(conf->eventname) + strlen(conf->groupname) + 3;
      conf->label = malloc(buf_sz);
      if (!conf->label) {
        // This is an error.  Technically we should probably just shut down the
        // application, but we'll pass an invalid conf instead
        free(conf->eventname);
        free(conf->groupname);
        memset(&conf, 0, sizeof(conf));
        return;
      }

      snprintf(conf->label, buf_sz - 1, "%s:%s", conf->eventname,
               conf->groupname);
    } else if (conf->eventname) {
      conf->label = strdup(conf->eventname);
    } else if (conf->id) {
      size_t buf_sz = strlen("id:") + 20 + 2; // 2^64 has 20 digits
      conf->label = malloc(buf_sz);
      if (!conf->label) {
        // This is an error.  Technically we should probably just shut down the
        // application, but we'll pass an invalid conf instead
        free(conf->eventname);
        free(conf->groupname);
        memset(&conf, 0, sizeof(conf));
        return;
      }

      snprintf(conf->label, buf_sz - 1, "id:%lu", conf->id);
    }
  }
}

void conf_print(const EventConf *tp) {
  if (tp->id)
    printf("  id: %lu\n", tp->id);
  else if (tp->groupname)
    printf("  tracepoint: %s:%s\n", tp->groupname, tp->eventname);
  else
    printf("  event: %s\n", tp->eventname);

  if (tp->label)
    printf("  label: %s\n", tp->label);
  else
    printf("  label: <generated from event/groupname>\n");
  
  const char *modenames[] = {"ILLEGAL", "callgraph", "metric", "metric and callgraph"};
  printf("  type: %s\n", modenames[tp->mode]);


  if (tp->loc_type  == ECLOC_VAL)
    printf("  location: value\n");
  else if (tp->loc_type == ECLOC_REG)
    printf("  location: parameter%d\n", tp->register_num);
  else if (tp->loc_type == ECLOC_RAW)
    printf("  location: raw event (%lu with size %d bytes)\n", tp->arg_offset, tp->arg_size);

  if (tp->arg_coeff != 0)
    printf("  coefficient: %f\n", tp->arg_coeff);

  printf("\n");

}

EventConf g_accum_event_conf = {0};

void yyerror(const char *str) {
#ifdef EVENT_PARSER_MAIN
  fprintf(stderr, "err: %s\n", str);
#endif 
}

#define VAL_ERROR() \
 do { \
   yyerror("Invalid value"); \
   YYABORT;  \
 } while(0)

EventConf *EventConf_parse(const char *msg) {
  memset(&g_accum_event_conf, 0, sizeof(g_accum_event_conf));
  int ret = -1;
  YY_BUFFER_STATE buffer = yy_scan_string(msg);
  ret = yyparse();
  yy_delete_buffer(buffer);
  return 0 == ret ? &g_accum_event_conf : NULL;
}

#ifdef EVENT_PARSER_MAIN
bool g_debugout_enable = false;
int main(int c, char **v) { 
  g_debugout_enable = false;
  if (c) {
    printf(">\"%s\"\n", v[1]);
    YY_BUFFER_STATE buffer = yy_scan_string(v[1]);
    g_debugout_enable = true;
    if (!yyparse())
      conf_print(&g_accum_event_conf);
    else
      fprintf(stderr, "  ERROR\n");
    yy_delete_buffer(buffer);
  } else {
    yyparse();
  }
  return 0;
}
#endif

#line 158 "event_parser.y"
typedef union {
	uint64_t num;
	char *str;
	char typ;
	double fpnum;
	EventConfField field;
} yy_event_parse_stype;
#define YY_event_parse_STYPE yy_event_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_event_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_event_parse_BISON 1

#ifndef YY_event_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_event_parse_COMPATIBILITY 1
 #else
  #define  YY_event_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_event_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_event_parse_LTYPE
   #define YY_event_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_event_parse_STYPE 
   #define YY_event_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_event_parse_DEBUG
   #define  YY_event_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_event_parse_USE_GOTO
  #define YY_event_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_event_parse_USE_GOTO
 #define YY_event_parse_USE_GOTO 0
#endif

#ifndef YY_event_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_event_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_event_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"
#define YY_event_parse_DEBUG 1

#line 136 "/usr/share/bison++/bison.cc"
/* YY_event_parse_DEBUG */
#endif


#ifndef YY_event_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_event_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_event_parse_LSP_NEEDED
#ifndef YY_event_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_event_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_event_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_event_parse_STYPE
#define YY_event_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_event_parse_PARSE
#define YY_event_parse_PARSE yyparse
#endif
#ifndef YY_event_parse_LEX
#define YY_event_parse_LEX yylex
#endif
#ifndef YY_event_parse_LVAL
#define YY_event_parse_LVAL yylval
#endif
#ifndef YY_event_parse_LLOC
#define YY_event_parse_LLOC yylloc
#endif
#ifndef YY_event_parse_CHAR
#define YY_event_parse_CHAR yychar
#endif
#ifndef YY_event_parse_NERRS
#define YY_event_parse_NERRS yynerrs
#endif
#ifndef YY_event_parse_DEBUG_FLAG
#define YY_event_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_event_parse_ERROR
#define YY_event_parse_ERROR yyerror
#endif

#ifndef YY_event_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_event_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_event_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_event_parse_PARSE_PARAM
  #define YY_event_parse_PARSE_PARAM void
 #endif
#endif

#if YY_event_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_event_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_event_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_event_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_event_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_event_parse_PURE
#  endif
#endif

#ifdef YY_event_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_event_parse_DEBUG 
#  endif
#endif

#ifndef YY_event_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_event_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_event_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_event_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	EQ	258
#define	OPTSEP	259
#define	CONFSEP	260
#define	FLOAT	261
#define	NUMBER	262
#define	HEXNUMBER	263
#define	WORD	264
#define	KEY	265


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_event_parse_CLASS
#define YY_event_parse_CLASS event_parse
#endif
#ifndef YY_event_parse_INHERIT
#define YY_event_parse_INHERIT
#endif
#ifndef YY_event_parse_MEMBERS
#define YY_event_parse_MEMBERS 
#endif
#ifndef YY_event_parse_LEX_BODY
#define YY_event_parse_LEX_BODY  
#endif
#ifndef YY_event_parse_ERROR_BODY
#define YY_event_parse_ERROR_BODY  
#endif
#ifndef YY_event_parse_CONSTRUCTOR_PARAM
#define YY_event_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_event_parse_CONSTRUCTOR_CODE
#define YY_event_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_event_parse_CONSTRUCTOR_INIT
#define YY_event_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_event_parse_USE_CONST_TOKEN
#define YY_event_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_event_parse_USE_CONST_TOKEN != 0
#ifndef YY_event_parse_ENUM_TOKEN
#define YY_event_parse_ENUM_TOKEN yy_event_parse_enum_token
#endif
#endif

class YY_event_parse_CLASS YY_event_parse_INHERIT
{
public: 
#if YY_event_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int EQ;
static const int OPTSEP;
static const int CONFSEP;
static const int FLOAT;
static const int NUMBER;
static const int HEXNUMBER;
static const int WORD;
static const int KEY;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_event_parse_ENUM_TOKEN { YY_event_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,EQ=258
	,OPTSEP=259
	,CONFSEP=260
	,FLOAT=261
	,NUMBER=262
	,HEXNUMBER=263
	,WORD=264
	,KEY=265


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_event_parse_PARSE (YY_event_parse_PARSE_PARAM);
 virtual void YY_event_parse_ERROR(char *msg) YY_event_parse_ERROR_BODY;
#ifdef YY_event_parse_PURE
#ifdef YY_event_parse_LSP_NEEDED
 virtual int  YY_event_parse_LEX (YY_event_parse_STYPE *YY_event_parse_LVAL,YY_event_parse_LTYPE *YY_event_parse_LLOC) YY_event_parse_LEX_BODY;
#else
 virtual int  YY_event_parse_LEX (YY_event_parse_STYPE *YY_event_parse_LVAL) YY_event_parse_LEX_BODY;
#endif
#else
 virtual int YY_event_parse_LEX() YY_event_parse_LEX_BODY;
 YY_event_parse_STYPE YY_event_parse_LVAL;
#ifdef YY_event_parse_LSP_NEEDED
 YY_event_parse_LTYPE YY_event_parse_LLOC;
#endif
 int   YY_event_parse_NERRS;
 int    YY_event_parse_CHAR;
#endif
#if YY_event_parse_DEBUG != 0
 int YY_event_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_event_parse_CLASS(YY_event_parse_CONSTRUCTOR_PARAM);
public:
 YY_event_parse_MEMBERS 
};
/* other declare folow */
#if YY_event_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_event_parse_CLASS::EQ=258;
const int YY_event_parse_CLASS::OPTSEP=259;
const int YY_event_parse_CLASS::CONFSEP=260;
const int YY_event_parse_CLASS::FLOAT=261;
const int YY_event_parse_CLASS::NUMBER=262;
const int YY_event_parse_CLASS::HEXNUMBER=263;
const int YY_event_parse_CLASS::WORD=264;
const int YY_event_parse_CLASS::KEY=265;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_event_parse_CLASS::token */
#endif
/*apres const  */
YY_event_parse_CLASS::YY_event_parse_CLASS(YY_event_parse_CONSTRUCTOR_PARAM) YY_event_parse_CONSTRUCTOR_INIT
{
#if YY_event_parse_DEBUG != 0
YY_event_parse_DEBUG_FLAG=0;
#endif
YY_event_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		19
#define	YYFLAG		-32768
#define	YYNTBASE	12

#define YYTRANSLATE(x) ((unsigned)(x) <= 265 ? yytranslate[x] : 16)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    11,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10
};

#if YY_event_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,     9,    13,    15,    17,    21,    27,    31,
    35,    37
};

static const short yyrhs[] = {    13,
     5,     0,    13,     0,    13,     4,    14,     0,    13,     4,
     9,     0,    14,     0,     9,     0,    10,     3,     9,     0,
    10,     3,     9,    11,     9,     0,    10,     3,    15,     0,
    10,     3,     6,     0,     7,     0,     8,     0
};

#endif

#if (YY_event_parse_DEBUG != 0) || defined(YY_event_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   179,   180,   183,   184,   185,   186,   189,   198,   204,   242,
   250,   250
};

static const char * const yytname[] = {   "$","error","$illegal.","EQ","OPTSEP",
"CONFSEP","FLOAT","NUMBER","HEXNUMBER","WORD","KEY","':'","confs","conf","opt",
"uinteger",""
};
#endif

static const short yyr1[] = {     0,
    12,    12,    13,    13,    13,    13,    14,    14,    14,    14,
    15,    15
};

static const short yyr2[] = {     0,
     2,     1,     3,     3,     1,     1,     3,     5,     3,     3,
     1,     1
};

static const short yydefact[] = {     0,
     6,     0,     2,     5,     0,     0,     1,    10,    11,    12,
     7,     9,     4,     3,     0,     8,     0,     0,     0
};

static const short yydefgoto[] = {    17,
     3,     4,    12
};

static const short yypact[] = {    -5,
-32768,     7,     2,-32768,    -6,    -1,-32768,-32768,-32768,-32768,
     0,-32768,-32768,-32768,     3,-32768,    13,    14,-32768
};

static const short yypgoto[] = {-32768,
-32768,     9,-32768
};


#define	YYLAST		15


static const short yytable[] = {     8,
     9,    10,    11,     1,     2,     6,     7,    13,     2,     5,
    15,    16,    18,    19,    14
};

static const short yycheck[] = {     6,
     7,     8,     9,     9,    10,     4,     5,     9,    10,     3,
    11,     9,     0,     0,     6
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_event_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_event_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_event_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_event_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_event_parse_CHAR = (token), YY_event_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_event_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_event_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_event_parse_PURE
/* UNPURE */
#define YYLEX           YY_event_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_event_parse_CHAR;                      /*  the lookahead symbol        */
YY_event_parse_STYPE      YY_event_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_event_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_event_parse_LSP_NEEDED
YY_event_parse_LTYPE YY_event_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_event_parse_LSP_NEEDED
#define YYLEX           YY_event_parse_LEX(&YY_event_parse_LVAL, &YY_event_parse_LLOC)
#else
#define YYLEX           YY_event_parse_LEX(&YY_event_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_event_parse_DEBUG != 0
int YY_event_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_event_parse_CLASS::
#endif
     YY_event_parse_PARSE(YY_event_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_event_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_event_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_event_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_event_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_event_parse_LSP_NEEDED
  YY_event_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_event_parse_LTYPE *yyls = yylsa;
  YY_event_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_event_parse_PURE
  int YY_event_parse_CHAR;
  YY_event_parse_STYPE YY_event_parse_LVAL;
  int YY_event_parse_NERRS;
#ifdef YY_event_parse_LSP_NEEDED
  YY_event_parse_LTYPE YY_event_parse_LLOC;
#endif
#endif

  YY_event_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_event_parse_NERRS = 0;
  YY_event_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_event_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_event_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_event_parse_LSP_NEEDED
      YY_event_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_event_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_event_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_event_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_event_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_event_parse_LSP_NEEDED
      yyls = (YY_event_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_event_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_event_parse_DEBUG != 0
      if (YY_event_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_event_parse_CHAR == YYEMPTY)
    {
#if YY_event_parse_DEBUG != 0
      if (YY_event_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_event_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_event_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_event_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_event_parse_DEBUG != 0
      if (YY_event_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_event_parse_CHAR);

#if YY_event_parse_DEBUG != 0
      if (YY_event_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_event_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_event_parse_CHAR, YY_event_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_event_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_event_parse_CHAR != YYEOF)
    YY_event_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_event_parse_LVAL;
#ifdef YY_event_parse_LSP_NEEDED
  *++yylsp = YY_event_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 179 "event_parser.y"
{ conf_finalize(&g_accum_event_conf); ;
    break;}
case 2:
#line 180 "event_parser.y"
{ conf_finalize(&g_accum_event_conf); ;
    break;}
case 3:
#line 183 "event_parser.y"
{ ;
    break;}
case 4:
#line 184 "event_parser.y"
{ ;
    break;}
case 5:
#line 185 "event_parser.y"
{ ;
    break;}
case 6:
#line 186 "event_parser.y"
{ g_accum_event_conf.eventname = yyvsp[0].str; ;
    break;}
case 7:
#line 189 "event_parser.y"
{
       switch(yyval.field) {
         case ECF_EVENT: g_accum_event_conf.eventname = yyvsp[0].str; break;
         case ECF_GROUP: g_accum_event_conf.groupname = yyvsp[0].str; break;
         case ECF_LABEL: g_accum_event_conf.label = yyvsp[0].str; break;
         case ECF_MODE:  g_accum_event_conf.mode |= mode_from_str(yyvsp[0].str); break;
         default: VAL_ERROR(); break;
       }
     ;
    break;}
case 8:
#line 198 "event_parser.y"
{
       if (yyval.field == ECF_EVENT || yyval.field == ECF_GROUP) {
         g_accum_event_conf.eventname = yyvsp[-2].str;
         g_accum_event_conf.groupname = yyvsp[0].str;
       }
     ;
    break;}
case 9:
#line 204 "event_parser.y"
{
       switch(yyval.field) {
         case ECF_ID: g_accum_event_conf.id = yyvsp[0].num; break;
         case ECF_ARGSIZE: g_accum_event_conf.arg_size= yyvsp[0].num; break;
         case ECF_ARGOFFSET: g_accum_event_conf.arg_offset = yyvsp[0].num; break;
         case ECF_ARGCOEFF: g_accum_event_conf.arg_coeff = 0.0 + yyvsp[0].num; break;
         case ECF_REGISTER: g_accum_event_conf.register_num = yyvsp[0].num; break;
         case ECF_MODE: g_accum_event_conf.mode = yyvsp[0].num & EVENT_BOTH; break;
         case ECF_PARAMETER:
           g_accum_event_conf.register_num = param_to_regno_c(yyvsp[0].num);
           break;
         default: VAL_ERROR(); break;
       }

       // If the location type hasn't been set yet, AND we're populating
       // metadata which implies a location, then set the location
       // note:  this means in the face of conflicting input, the first type
       //        of configuration is preferred
       if (!g_accum_event_conf.loc_type) {
         switch(yyval.field) {
           case ECF_PARAMETER: g_accum_event_conf.loc_type = ECLOC_REG; break;
           case ECF_REGISTER: g_accum_event_conf.loc_type = ECLOC_REG; break;
           case ECF_ARGOFFSET: g_accum_event_conf.loc_type = ECLOC_RAW; break;
           default: VAL_ERROR(); break;
         }
       }

       // Only set cadence if it has yet to be specified
       if (!g_accum_event_conf.cad_type) {
         if (yyval.field == ECF_PERIOD) {
           g_accum_event_conf.cadence = yyvsp[0].num; break;
           g_accum_event_conf.cad_type = ECCAD_PERIOD;
         } else if (yyval.field == ECF_FREQUENCY) {
           g_accum_event_conf.cadence = yyvsp[0].num; break;
           g_accum_event_conf.cad_type = ECCAD_FREQ;
         }
       }
     ;
    break;}
case 10:
#line 242 "event_parser.y"
{
       if (yyval.field == ECF_ARGCOEFF)
         g_accum_event_conf.arg_coeff = yyvsp[0].fpnum;
       else
         VAL_ERROR();
     ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_event_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_event_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_event_parse_LLOC.first_line;
      yylsp->first_column = YY_event_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_event_parse_NERRS;

#ifdef YY_event_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_event_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_event_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_event_parse_ERROR_VERBOSE */
	YY_event_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_event_parse_CHAR == YYEOF)
	YYABORT;

#if YY_event_parse_DEBUG != 0
      if (YY_event_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_event_parse_CHAR, yytname[yychar1]);
#endif

      YY_event_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_event_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_event_parse_DEBUG != 0
  if (YY_event_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_event_parse_LVAL;
#ifdef YY_event_parse_LSP_NEEDED
  *++yylsp = YY_event_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 251 "event_parser.y"
