// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0. This product includes software
// developed at Datadog (https://www.datadoghq.com/). Copyright 2021-Present
// Datadog, Inc.

#include "dwarf_helpers.hpp"

#include "logger.hpp"

#include <map>
#include <string>

namespace ddprof {

const char *get_attribute_name(int attrCode) {
  // Should not get init unless cablled
  // Something like following awk can help generate this map:
  // cat file_with_dwarf_attributes.txt |
  //      awk '!/\/\*/ { print  "{ "$1", \""$1"\"},"}'
  static const std::map<int, std::string> attributeNameMap = {
      {DW_AT_sibling, "DW_AT_sibling"},
      {DW_AT_location, "DW_AT_location"},
      {DW_AT_name, "DW_AT_name"},
      {DW_AT_ordering, "DW_AT_ordering"},
      {DW_AT_byte_size, "DW_AT_byte_size"},
      {DW_AT_bit_size, "DW_AT_bit_size"},
      {DW_AT_stmt_list, "DW_AT_stmt_list"},
      {DW_AT_low_pc, "DW_AT_low_pc"},
      {DW_AT_high_pc, "DW_AT_high_pc"},
      {DW_AT_language, "DW_AT_language"},
      {DW_AT_discr, "DW_AT_discr"},
      {DW_AT_discr_value, "DW_AT_discr_value"},
      {DW_AT_visibility, "DW_AT_visibility"},
      {DW_AT_import, "DW_AT_import"},
      {DW_AT_string_length, "DW_AT_string_length"},
      {DW_AT_common_reference, "DW_AT_common_reference"},
      {DW_AT_comp_dir, "DW_AT_comp_dir"},
      {DW_AT_const_value, "DW_AT_const_value"},
      {DW_AT_containing_type, "DW_AT_containing_type"},
      {DW_AT_default_value, "DW_AT_default_value"},
      {DW_AT_inline, "DW_AT_inline"},
      {DW_AT_is_optional, "DW_AT_is_optional"},
      {DW_AT_lower_bound, "DW_AT_lower_bound"},
      {DW_AT_producer, "DW_AT_producer"},
      {DW_AT_prototyped, "DW_AT_prototyped"},
      {DW_AT_return_addr, "DW_AT_return_addr"},
      {DW_AT_start_scope, "DW_AT_start_scope"},
      {DW_AT_bit_stride, "DW_AT_bit_stride"},
      {DW_AT_upper_bound, "DW_AT_upper_bound"},
      {DW_AT_abstract_origin, "DW_AT_abstract_origin"},
      {DW_AT_accessibility, "DW_AT_accessibility"},
      {DW_AT_address_class, "DW_AT_address_class"},
      {DW_AT_artificial, "DW_AT_artificial"},
      {DW_AT_base_types, "DW_AT_base_types"},
      {DW_AT_calling_convention, "DW_AT_calling_convention"},
      {DW_AT_count, "DW_AT_count"},
      {DW_AT_data_member_location, "DW_AT_data_member_location"},
      {DW_AT_decl_column, "DW_AT_decl_column"},
      {DW_AT_decl_file, "DW_AT_decl_file"},
      {DW_AT_decl_line, "DW_AT_decl_line"},
      {DW_AT_declaration, "DW_AT_declaration"},
      {DW_AT_discr_list, "DW_AT_discr_list"},
      {DW_AT_encoding, "DW_AT_encoding"},
      {DW_AT_external, "DW_AT_external"},
      {DW_AT_frame_base, "DW_AT_frame_base"},
      {DW_AT_friend, "DW_AT_friend"},
      {DW_AT_identifier_case, "DW_AT_identifier_case"},
      {DW_AT_namelist_item, "DW_AT_namelist_item"},
      {DW_AT_priority, "DW_AT_priority"},
      {DW_AT_segment, "DW_AT_segment"},
      {DW_AT_specification, "DW_AT_specification"},
      {DW_AT_static_link, "DW_AT_static_link"},
      {DW_AT_type, "DW_AT_type"},
      {DW_AT_use_location, "DW_AT_use_location"},
      {DW_AT_variable_parameter, "DW_AT_variable_parameter"},
      {DW_AT_virtuality, "DW_AT_virtuality"},
      {DW_AT_vtable_elem_location, "DW_AT_vtable_elem_location"},
      {DW_AT_allocated, "DW_AT_allocated"},
      {DW_AT_associated, "DW_AT_associated"},
      {DW_AT_data_location, "DW_AT_data_location"},
      {DW_AT_byte_stride, "DW_AT_byte_stride"},
      {DW_AT_entry_pc, "DW_AT_entry_pc"},
      {DW_AT_use_UTF8, "DW_AT_use_UTF8"},
      {DW_AT_extension, "DW_AT_extension"},
      {DW_AT_ranges, "DW_AT_ranges"},
      {DW_AT_trampoline, "DW_AT_trampoline"},
      {DW_AT_call_column, "DW_AT_call_column"},
      {DW_AT_call_file, "DW_AT_call_file"},
      {DW_AT_call_line, "DW_AT_call_line"},
      {DW_AT_description, "DW_AT_description"},
      {DW_AT_binary_scale, "DW_AT_binary_scale"},
      {DW_AT_decimal_scale, "DW_AT_decimal_scale"},
      {DW_AT_small, "DW_AT_small"},
      {DW_AT_decimal_sign, "DW_AT_decimal_sign"},
      {DW_AT_digit_count, "DW_AT_digit_count"},
      {DW_AT_picture_string, "DW_AT_picture_string"},
      {DW_AT_mutable, "DW_AT_mutable"},
      {DW_AT_threads_scaled, "DW_AT_threads_scaled"},
      {DW_AT_explicit, "DW_AT_explicit"},
      {DW_AT_object_pointer, "DW_AT_object_pointer"},
      {DW_AT_endianity, "DW_AT_endianity"},
      {DW_AT_elemental, "DW_AT_elemental"},
      {DW_AT_pure, "DW_AT_pure"},
      {DW_AT_recursive, "DW_AT_recursive"},
      {DW_AT_signature, "DW_AT_signature"},
      {DW_AT_main_subprogram, "DW_AT_main_subprogram"},
      {DW_AT_data_bit_offset, "DW_AT_data_bit_offset"},
      {DW_AT_const_expr, "DW_AT_const_expr"},
      {DW_AT_enum_class, "DW_AT_enum_class"},
      {DW_AT_linkage_name, "DW_AT_linkage_name"},
      {DW_AT_string_length_bit_size, "DW_AT_string_length_bit_size"},
      {DW_AT_string_length_byte_size, "DW_AT_string_length_byte_size"},
      {DW_AT_rank, "DW_AT_rank"},
      {DW_AT_str_offsets_base, "DW_AT_str_offsets_base"},
      {DW_AT_addr_base, "DW_AT_addr_base"},
      {DW_AT_rnglists_base, "DW_AT_rnglists_base"},
      {DW_AT_dwo_name, "DW_AT_dwo_name"},
      {DW_AT_reference, "DW_AT_reference"},
      {DW_AT_rvalue_reference, "DW_AT_rvalue_reference"},
      {DW_AT_macros, "DW_AT_macros"},
      {DW_AT_call_all_calls, "DW_AT_call_all_calls"},
      {DW_AT_call_all_source_calls, "DW_AT_call_all_source_calls"},
      {DW_AT_call_all_tail_calls, "DW_AT_call_all_tail_calls"},
      {DW_AT_call_return_pc, "DW_AT_call_return_pc"},
      {DW_AT_call_value, "DW_AT_call_value"},
      {DW_AT_call_origin, "DW_AT_call_origin"},
      {DW_AT_call_parameter, "DW_AT_call_parameter"},
      {DW_AT_call_pc, "DW_AT_call_pc"},
      {DW_AT_call_tail_call, "DW_AT_call_tail_call"},
      {DW_AT_call_target, "DW_AT_call_target"},
      {DW_AT_call_target_clobbered, "DW_AT_call_target_clobbered"},
      {DW_AT_call_data_location, "DW_AT_call_data_location"},
      {DW_AT_call_data_value, "DW_AT_call_data_value"},
      {DW_AT_noreturn, "DW_AT_noreturn"},
      {DW_AT_alignment, "DW_AT_alignment"},
      {DW_AT_export_symbols, "DW_AT_export_symbols"},
      {DW_AT_deleted, "DW_AT_deleted"},
      {DW_AT_defaulted, "DW_AT_defaulted"},
      {DW_AT_loclists_base, "DW_AT_loclists_base"},
      {DW_AT_lo_user, "DW_AT_lo_user"},
      {DW_AT_MIPS_fde, "DW_AT_MIPS_fde"},
      {DW_AT_MIPS_loop_begin, "DW_AT_MIPS_loop_begin"},
      {DW_AT_MIPS_tail_loop_begin, "DW_AT_MIPS_tail_loop_begin"},
      {DW_AT_MIPS_epilog_begin, "DW_AT_MIPS_epilog_begin"},
      {DW_AT_MIPS_loop_unroll_factor, "DW_AT_MIPS_loop_unroll_factor"},
      {DW_AT_MIPS_software_pipeline_depth,
       "DW_AT_MIPS_software_pipeline_depth"},
      {DW_AT_MIPS_linkage_name, "DW_AT_MIPS_linkage_name"},
      {DW_AT_MIPS_stride, "DW_AT_MIPS_stride"},
      {DW_AT_MIPS_abstract_name, "DW_AT_MIPS_abstract_name"},
      {DW_AT_MIPS_clone_origin, "DW_AT_MIPS_clone_origin"},
      {DW_AT_MIPS_has_inlines, "DW_AT_MIPS_has_inlines"},
      {DW_AT_MIPS_stride_byte, "DW_AT_MIPS_stride_byte"},
      {DW_AT_MIPS_stride_elem, "DW_AT_MIPS_stride_elem"},
      {DW_AT_MIPS_ptr_dopetype, "DW_AT_MIPS_ptr_dopetype"},
      {DW_AT_MIPS_allocatable_dopetype, "DW_AT_MIPS_allocatable_dopetype"},
      {DW_AT_MIPS_assumed_shape_dopetype, "DW_AT_MIPS_assumed_shape_dopetype"},
      {DW_AT_MIPS_assumed_size, "DW_AT_MIPS_assumed_size"},
      {DW_AT_sf_names, "DW_AT_sf_names"},
      {DW_AT_src_info, "DW_AT_src_info"},
      {DW_AT_mac_info, "DW_AT_mac_info"},
      {DW_AT_src_coords, "DW_AT_src_coords"},
      {DW_AT_body_begin, "DW_AT_body_begin"},
      {DW_AT_body_end, "DW_AT_body_end"},
      {DW_AT_GNU_vector, "DW_AT_GNU_vector"},
      {DW_AT_GNU_guarded_by, "DW_AT_GNU_guarded_by"},
      {DW_AT_GNU_pt_guarded_by, "DW_AT_GNU_pt_guarded_by"},
      {DW_AT_GNU_guarded, "DW_AT_GNU_guarded"},
      {DW_AT_GNU_pt_guarded, "DW_AT_GNU_pt_guarded"},
      {DW_AT_GNU_locks_excluded, "DW_AT_GNU_locks_excluded"},
      {DW_AT_GNU_exclusive_locks_required,
       "DW_AT_GNU_exclusive_locks_required"},
      {DW_AT_GNU_shared_locks_required, "DW_AT_GNU_shared_locks_required"},
      {DW_AT_GNU_odr_signature, "DW_AT_GNU_odr_signature"},
      {DW_AT_GNU_template_name, "DW_AT_GNU_template_name"},
      {DW_AT_GNU_call_site_value, "DW_AT_GNU_call_site_value"},
      {DW_AT_GNU_call_site_data_value, "DW_AT_GNU_call_site_data_value"},
      {DW_AT_GNU_call_site_target, "DW_AT_GNU_call_site_target"},
      {DW_AT_GNU_call_site_target_clobbered,
       "DW_AT_GNU_call_site_target_clobbered"},
      {DW_AT_GNU_tail_call, "DW_AT_GNU_tail_call"},
      {DW_AT_GNU_all_tail_call_sites, "DW_AT_GNU_all_tail_call_sites"},
      {DW_AT_GNU_all_call_sites, "DW_AT_GNU_all_call_sites"},
      {DW_AT_GNU_all_source_call_sites, "DW_AT_GNU_all_source_call_sites"},
      {DW_AT_GNU_locviews, "DW_AT_GNU_locviews"},
      {DW_AT_GNU_entry_view, "DW_AT_GNU_entry_view"},
      {DW_AT_GNU_macros, "DW_AT_GNU_macros"},
      {DW_AT_GNU_deleted, "DW_AT_GNU_deleted"},
      {DW_AT_GNU_dwo_name, "DW_AT_GNU_dwo_name"},
      {DW_AT_GNU_dwo_id, "DW_AT_GNU_dwo_id"},
      {DW_AT_GNU_ranges_base, "DW_AT_GNU_ranges_base"},
      {DW_AT_GNU_addr_base, "DW_AT_GNU_addr_base"},
      {DW_AT_GNU_pubnames, "DW_AT_GNU_pubnames"},
      {DW_AT_GNU_pubtypes, "DW_AT_GNU_pubtypes"},
      {DW_AT_GNU_numerator, "DW_AT_GNU_numerator"},
      {DW_AT_GNU_denominator, "DW_AT_GNU_denominator"},
      {DW_AT_GNU_bias, "DW_AT_GNU_bias"},
      {DW_AT_hi_user, "DW_AT_hi_user"},
  };
  auto it = attributeNameMap.find(attrCode);
  if (it != attributeNameMap.end()) {
    return it->second.c_str();
  }
  return "Unknown Attribute";
}

int print_attribute(Dwarf_Attribute *attr, void *arg) {
  // Extract information from the attribute and print it
  // For example, you might want to print the attribute's name and value
  // The implementation depends on how you want to display the attributes
  LG_DBG("Attribute code %x(%s) - form %d", attr->code,
         get_attribute_name(attr->code), attr->form);
  // Return a non-zero value to continue iterating through attributes
  return 0;
}
} // namespace ddprof
